protect_before_launch.settings:
  type: config_object
  label: 'Module Settings'
  mapping:
    protect:
      type: integer
      label: 'Enable protection mode'
    username:
      type: string
      label: 'Username'
    realm:
      type: string
      label: 'Password'
    exclude_paths:
      type: string
      label: 'Paths excluded'
    password:
      type: string
      label: 'Password'
    content:
      type: string
      label: 'Replacement content'
    environment_key:
      type: string
      label: 'Environment Key'
    environment_value:
      type: string
      label: 'Environment Value'
    authentication_type:
      type: integer
      label: 'Identity provider'
